config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :body, presence: true
  validates :title, presence: true
  validates :user, presence: true
  validates :question, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  validates :username, presence: true

  def self.find_or_create_from_omniauth(auth)
    provider = auth.provider
    uid = auth.uid


    find_by(provider: provider, uid: uid) || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create(
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email,
      username: auth.info.nickname,
      avatar_url: auth.info.image
    )
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new(question: @question)
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(params.require(:answer).permit(:title, :body))
    @answer.question = @question
    @answer.user = User.last
    @answer.save

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully submitted.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { redirect_to new_question_answer_path, notice: 'Please fill out both fields' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(question: @question)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.order('created_at DESC')
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = User.first
    @question.save

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { redirect_to new_question_path, notice: 'Please fill in both fields'}
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  def update
    @question = Question.find(params[:id])
    # redirect_to question_path(params[:id])

    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
      else
        format.html { redirect_to new_question_path, notice: 'Please fill in both fields'}
      end
    end

  end

  def edit
    @question = Question.find(params[:id])
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
      user_id = session[:user_id]
      @current_user ||= User.find(user_id) if user_id.present?
    end

    def signed_in?
      current_user.present?
    end

  def set_current_user(user)
    session[:user_id] = user.id
  end

  def authenticate!
    unless signed_in?
      flash[:notice] = "You need to sign in if you want to do that!"
      redirect '/'
    end
  end

end

app/views/answers/new.html.erb
<%= render "layouts/flash" %>

<h1>Submit an Answer</h1>

  <%= form_for @answer, url: {action: "create"} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit "Submit answer" %>
  <% end %>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |notice| %>
    <p class="flash"><%= notice[1] %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Your Question</h1>

  <%= form_for @question do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit "Submit Edited Question" %>
  <% end %>

app/views/questions/index.html.erb
<table class="table">
  <tr>
    <th>Question</th>
    <th>Asked By</th>
    <th>Updated</th>
    <th>Delete?</th>
    <th>Edit<th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= link_to question.title, question_path(question.id)%></td>
      <td><%= question.user.username %></td>
      <td><%= question.created_at %></td>
      <td><%= link_to 'Delete', question_path(question.id), method: :delete %></td>
      <td><%= link_to 'Edit', edit_question_path(question.id) %></td>
    <tr>
  <% end %>
</table>

<%= link_to "Ask a new question", new_question_path %>

app/views/questions/new.html.erb
<%= render "layouts/flash" %>

<h1>Ask a Question</h1>

  <%= form_for @question, url: {action: "create"} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit "Ask Question" %>
  <% end %>

app/views/questions/show.html.erb
<div class="row">
<div class="small-2 large-4 columns">

<%= render "layouts/flash" %>

<div class="question">
<h2><%= @question.title %></h1>
  <p>Asked by <%= @question.user.username %></p>
  <p>Asked at <%= @question.created_at %>
  <p><%= @question.body %></p>
  <%= link_to 'Edit', edit_question_path(@question.id) %>
</div>
</div>
</div>

<div class="row">

<h4>Answers</h4>
<% if @question.answers.length != 0 %>
  <% @question.answers.each do |answer| %>
    <div class="large-4 columns answer end">
    <span><%= answer.user.username %> responded: </span>
    <h4><%= answer.title %></h4>
    <span><%= answer.body %></span>
    <p>Best? <%= answer.best %></p>
      <%= check_box_tag(:best) %>
  	  <%= label_tag(:best) %>
    </div>
  <% end %>
<% else %>
  <p>This question does not yet have any answers<p>
<% end %>
</div>

<div class="row">
<div class="small-4 large-4 large-offset-10 columns">
<p><%= link_to "Submit an Answer", new_question_answer_path(params[:id]) %></p>
<p><%= link_to "Home", questions_path %></p>
</div>
</div>